### ISSUE TITLE
InviteTracker throwing error bc of matplotlib

### ISSUE THREAD

**Issue by karutoil** [BeeHiveCyberSecurity/BeeHive-Cogs#5]
```py
Exception during loading of package
Traceback (most recent call last):
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 189, in _load
    await bot.load_extension(spec)
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/bot.py", line 1684, in load_extension
    lib = spec.loader.load_module()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1120, in load_module
  File "<frozen importlib._bootstrap_external>", line 945, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.local/share/Red-DiscordBot/data/heaviside/cogs/CogManager/cogs/invitetracker/__init__.py", line 3, in <module>
    from .invitetracker import InviteTracker
  File "/root/.local/share/Red-DiscordBot/data/heaviside/cogs/CogManager/cogs/invitetracker/invitetracker.py", line 3, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```

**Comment by BeeHiveCyberSecurity** [comment]
Hi @karutoil 

`matplotlib` was left out of the bot's requirements in `info.json`, it's now been added.

For a clean load trial, please uninstall the `invitetracker` cog, then reinstall it from the most up to date code available in this repo using `[p]cog install beehive-cogs invitetracker`

If this error continues, please let us know and we'll look into it elsewhere.

**Comment by BeeHiveCyberSecurity** [comment]
Hi @karutoil 

Upon further testing and reinstalls, we're not able to reproduce this issue further and haven't heard back from you. We'll close this issue - but if it reoccurs, or you have another, please feel free to open another issue and we'll sort it out for you. 

Thank you <3
